sudo: false
language: node_js
node_js:
  - "8"

# Need to specify a GCC compiler now!
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install
  - cd themes/tranquilpeak
  - npm install --production
  - cd ../../
  - pwd

before_script:

script:
  - npm run gen

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  target_branch: master
  fqdn: www.uifx.com
  on:
    branch: source

notifications:
  email:
    recipients:
      - u_glow@hotmail.com

