source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-coffeescript'
gem 'jekyll-sass-converter'
gem 'jekyll-paginate'
gem 'jekyll-gist'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'